# Generated by Django 3.2.25 on 2025-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://png.pngtree.com/png-vector/20190711/ourmid/pngtree-cook-icon-for-your-project-png-image_1541448.jpg', max_length=500),
        ),
    ]
